source 'https://github.com/vjieshao/Arithmetic_Specs.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'ArithmeticPlayer_Example' do
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!

end
