# 指定全局 iOS 平台版本
platform :ios, '13.0'

# 指定项目文件
project 'LearnMath.xcodeproj'

# 主 target
target 'LearnMath' do
  use_modular_headers!


  # 项目依赖
  pod 'Masonry'
  pod 'LookinServer', :configurations => ['Debug']
  pod 'FMDB'

  # 本地 Pod
pod 'SevenSwitch', :path => '../LearnMath/Frameworks/SevenSwitch'
pod 'ArithmeticPlayer', :path => '../LearnMath/Frameworks/ArithmeticPlayer'
pod 'EZPlayer', :path => '../LearnMath/Frameworks/EZPlayer'
pod 'AppToolKit', :path => '../LearnMath/Frameworks/AppToolKit'
pod 'AppearanceKit', :path => '../LearnMath/Frameworks/AppearanceKit'
pod 'AppStoreKit', :path => '../LearnMath/Frameworks/AppStoreKit'
pod 'ArithmeticKit', :path => '../LearnMath/Frameworks/ArithmeticKit'
pod 'AnalyticsTracker', :path => '../LearnMath/Frameworks/AnalyticsTracker'
pod 'ProgressHUD', :path => '../LearnMath/Frameworks/ProgressHUD'
pod 'ArithmeticStoreKit', :path => '../LearnMath/Frameworks/ArithmeticStoreKit'
pod 'ProviderError', :path => '../LearnMath/Frameworks/ProviderError'
pod 'DbService', :path => '../LearnMath/Frameworks/DbService'


end

# 全局 post_install
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # 统一部署目标
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'

      # 强制主 target 和本地 Pod 使用 Swift 5
      if ['LearnMath', 'SevenSwitch'].include?(target.name)
        config.build_settings['SWIFT_VERSION'] = '5.0'
      end

      # 主 target 嵌入 Swift 标准库
      if target.name == 'LearnMath'
        config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'YES'
      end
    end
  end
end
