source 'git@github.com:Nuevo-Mundo/Emperor_iOS.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'ProviderError_Example' do
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!

end
